# vim Dcokerfile_mariaDB_01

FROM mariadb:10.6.3

ENV MYSQL_ROOT_PASSWORD=root 

ENV MYSQL_DATABASE=flask01_db 

ENV MYSQL_USER=flask01

ENV MYSQL_PASSWORD=flask01 

COPY my.cnf /etc/mysql/my.cnf  

EXPOSE 3000 

CMD ["mysqld"] 