# vim docker-compose.yml
version: '3.0'  # version 정의
services:  # service 아래단에 정의
  main:  # main에 관련
    build:
      context: .
      dockerfile: ./Dockerfile_main  # build 시킬 dockerfile
    image: main:0.0  # 사용자 지정 image 이름
    ports:
     - "80:8000"  # open port 설정
    networks:
     - project_network  # network 설정

  flask01:  # flask01에 관련
    build:
      context: .
      dockerfile: ./Dockerfile_python_01  # build 시킬 dockerfile
    image: flask01:0.0  # 사용자 지정 image 이름
    ports:
     - "8081:8000"  # open port 설정
    networks:
     - project_network  # network 설정

  flask02:
    build:
      context: .
      dockerfile: ./Dockerfile_python_02
    image: flask02:0.0
    ports:
     - "8082:8000"
    networks:
     - project_network

  mariadb01:  # mariadb01에 관련
    build:
      context: .
      dockerfile: ./Dockerfile_mariaDB_01  # build할 dockerfile 지정
    image: mariadb01:0.0  # 사용자 지정 image 이름
    volumes:  
      - mariadb:/var/lib/mysql  # volume 설정, my.cnf에 정의
    networks:
      - project_network  # network 설정

  mariadb02:
    build:
      context: .
      dockerfile: ./Dockerfile_mariaDB_02
    image: mariadb02:0.0
    volumes:
     - mariadb2:/var/lib/mysql
    networks:
     - project_network
volumes:  # volume 정의
  mariadb:
    external: true  # 기존의 볼륨을 사용하도록 설정
  mariadb2:
    external: true
networks:
  project_network:
    external: true  # 기존의 네트워크를 사용하도록 설정