FROM python:3.8

WORKDIR /backend
RUN pip install --upgrade pip

ENV FLASK_APP=app:app
COPY requirements.txt /backend/
RUN pip install -r requirements.txt
COPY . ./

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

CMD ["python", "./src/app.py"]  # python app.py 실행