FROM python:3.8

WORKDIR /backend
RUN pip install --upgrade pip

ENV FLASK_APP=app:app
COPY requirements.txt /backend/
RUN pip install -r requirements.txt
COPY . ./

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]